CREATE SEQUENCE SEQ_APP_USER_ID
START WITH 1
INCREMENT BY 1
CACHE 1;

CREATE SEQUENCE SEQ_LIST_ITEM_ID
START WITH 1
INCREMENT BY 1
CACHE 100;

CREATE TABLE APP_USER (
    id INTEGER DEFAULT nextval('SEQ_APP_USER_ID'::regclass) NOT NULL UNIQUE,
    username VARCHAR(30) NOT NULL,
    display_name varchar(30) NOT NULL
);

CREATE TABLE LIST_ITEM (
    id INTEGER DEFAULT nextval('SEQ_LIST_ITEM_ID'::regclass) NOT NULL UNIQUE,
    user_id INTEGER REFERENCES APP_USER(id) NOT NULL,
    value varchar(4000) NOT NULL
);