//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package ru.vkaretko.listmanager.web.service.soap;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

@WebService(name = "UserSoapService", targetNamespace = "http://soap.service.web.listmanager.vkaretko.ru/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface UserSoapService {


    /**
     * 
     * @param userName
     * @return
     *     returns java.lang.Long
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getUserId", targetNamespace = "http://soap.service.web.listmanager.vkaretko.ru/", className = "ru.vkaretko.listmanager.web.service.soap.GetUserId")
    @ResponseWrapper(localName = "getUserIdResponse", targetNamespace = "http://soap.service.web.listmanager.vkaretko.ru/", className = "ru.vkaretko.listmanager.web.service.soap.GetUserIdResponse")
    @Action(input = "http://soap.service.web.listmanager.vkaretko.ru/UserSoapService/getUserIdRequest", output = "http://soap.service.web.listmanager.vkaretko.ru/UserSoapService/getUserIdResponse")
    public Long getUserId(
        @WebParam(name = "userName", targetNamespace = "")
        String userName);

    /**
     * 
     * @param userId
     * @return
     *     returns java.util.List<ru.vkaretko.listmanager.web.service.soap.ListItem>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getUserListItems", targetNamespace = "http://soap.service.web.listmanager.vkaretko.ru/", className = "ru.vkaretko.listmanager.web.service.soap.GetUserListItems")
    @ResponseWrapper(localName = "getUserListItemsResponse", targetNamespace = "http://soap.service.web.listmanager.vkaretko.ru/", className = "ru.vkaretko.listmanager.web.service.soap.GetUserListItemsResponse")
    @Action(input = "http://soap.service.web.listmanager.vkaretko.ru/UserSoapService/getUserListItemsRequest", output = "http://soap.service.web.listmanager.vkaretko.ru/UserSoapService/getUserListItemsResponse")
    public List<ListItem> getUserListItems(
        @WebParam(name = "userId", targetNamespace = "")
        Long userId);

}
